from ..service.orders.aircraft_service import AircraftService
from ..service.orders.pitol_service import PilotService
from ..service.orders.current_location_service import CurrentLocationService
from ..service.orders.flight_history_service import FlightHistoryService
from ..service.orders.maintenance_service import MaintenanceService
from ..service.orders.flight_service import FlightService
from ..service.orders.airline_service import AirlineService
from ..service.orders.airport_service import AirportService
from ..service.orders.route_service import RouteService
from ..service.orders.crew_assignment_service import CrewAssignmentService
